# Generated by Django 4.1.3 on 2022-11-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprogramm',
            name='gender',
            field=models.CharField(blank=True, choices=[('Женщина', 'Женщина'), ('Мужчина', 'Мужчина')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Низкая', 'Низкая'), ('Умеренная', 'Умеренная'), ('Средняя', 'Средняя'), ('Большая', 'Большая')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='part_of_body',
            field=models.CharField(blank=True, choices=[('Руки', 'Руки'), ('Грудь', 'Грудь'), ('Спина', 'Спина'), ('Живот', 'Живот'), ('Ягодицы', 'Ягодицы'), ('Ноги', 'Ноги')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitnessprogramm',
            name='type',
            field=models.CharField(blank=True, choices=[('Для похудения', 'Для похудения'), ('Для набора мышечной мыссы', 'Для набора мышечной мыссы')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
