# Generated by Django 4.1.3 on 2022-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_fitnessprogramm_gender_fitnessprogramm_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite_slug',
            field=models.SlugField(verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorite_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='gender',
            field=models.CharField(blank=True, choices=[('Женщина', 'Женщина'), ('Мужчина', 'Мужчина')], max_length=255, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='intensity',
            field=models.CharField(blank=True, choices=[('Низкая интенсивность', 'Низкая интенсивность'), ('Умеренная интенсивность', 'Умеренная интенсивность'), ('Средняя интенсивность', 'Средняя интенсивность'), ('Большая интенсивность', 'Большая интенсивность')], max_length=255, null=True, verbose_name='Вид Интенсивности'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='part_of_body',
            field=models.CharField(blank=True, choices=[('Руки', 'Руки'), ('Грудь', 'Грудь'), ('Спина', 'Спина'), ('Живот', 'Живот'), ('Ягодицы', 'Ягодицы'), ('Ноги', 'Ноги')], max_length=255, null=True, verbose_name='Часть тела'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='slug',
            field=models.SlugField(verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='fitnessprogramm',
            name='type',
            field=models.CharField(blank=True, choices=[('Для похудения', 'Для похудения'), ('Для набора мышечной массы', 'Для набора мышечной массы')], max_length=255, null=True, verbose_name='Тип программы'),
        ),
    ]
